### PR TITLE
Defer loading gnome keyring specific interfaces

### LINKED ISSUE #34: Working with other secret service implementations
The [Secret Service API 0.2](https://specifications.freedesktop.org/secret-service/0.2) as been a published standard for quite some time and is now implemented by other services including:
- [KeepassXC](https://avaldes.co/2020/01/28/secret-service-keepassxc.html)
- KWallet ([as of version 5.97](https://invent.kde.org/frameworks/kwallet/-/merge_requests/11)

However, if something tries to use `SimpleCollection` with one of those instead of gnome-keyring, it [just crashes](https://github.com/swiesend/secret-service/blob/46a49680fdabfa1998ad9b76a5dafca43f2d2e4b/src/main/java/org/freedesktop/secret/simple/SimpleCollection.java#L248) with:
```
IOException(""The secret service is not available.")
```
because the [org.gnome.keyring](https://github.com/swiesend/secret-service/blob/46a49680fdabfa1998ad9b76a5dafca43f2d2e4b/src/main/java/org/freedesktop/secret/simple/SimpleCollection.java#L182) dbus service is not available.

Is it possible to defer that check?
To only crash if someone tries to use a gnome-specific feature?

### PR DESCRIPTION
**Pull request by shocklateboy92**
Now that there are other implementations of org.freedesktop.secrets, it makes sense to try using the interfaces that are part of the spec first.

This patch changes SimpleCollection to only use gnome specific methods when required, instead of at the start.

Fixes #34 

PS: I run all the tests with gnome-keyring installed after this change, and all the tests that passed on master continued to pass. (Reasonably certain I didn't regress any features).

### CODE REVIEW

**Comment by swiesend** [comment]
Ok, I have checked it locally. Running with and without the `gnome-keyring-daemon`. And checking with `d-feet` if the `InternalUnsupportedGuiltRiddenInterface` was present or not.

LGTM

File: src/main/java/org/freedesktop/secret/simple/SimpleCollection.java [hunk 1]
```diff
@@ -206,6 +205,36 @@ public static boolean isAvailable() {
...
+    public static boolean isGnomeKeyringAvailable() {
+        if (connection != null && connection.isConnected()) {
+            try {
+                DBus bus = connection.getRemoteObject(
+                        Static.DBus.Service.DBUS,
+                        Static.DBus.ObjectPaths.DBUS,
+                        DBus.class);
+                List<String> names = Arrays.asList(bus.ListNames());
+                if (!(names.contains(
+                        org.gnome.keyring.Static.Service.KEYRING))) {
```
Comment (swiesend) [inline src/main/java/org/freedesktop/secret/simple/SimpleCollection.java:223]: Maybe it would be better to check if the actual `InternalUnsupportedGuiltRiddenInterface` is exposed and not only if the `gnome-keyring` is present. As the `gnome-keyring-daemon` also starts the `ssh-agent`. But this is somewhat of an edge case, which in practice should not be relevant, as one either installs the `gnome-keyring` and uses it mostly with default config or does not use it at all.

Comment (swiesend) [reply src/main/java/org/freedesktop/secret/simple/SimpleCollection.java:223]:
```
/usr/bin/gnome-keyring-daemon --daemonize --login

/usr/bin/gnome-keyring-daemon --start --components=ssh
  /usr/bin/ssh-agent -D -a /run/user/1000/keyring/.ssh

/usr/bin/gnome-keyring-daemon --start --foreground --component=secrets
```

Comment (swiesend) [reply src/main/java/org/freedesktop/secret/simple/SimpleCollection.java:223]: The only method failing, when the `gnome-keyring-daemon` is not running is `isLocked()`. Invoking the [test for `isLocked()`](https://github.com/swiesend/secret-service/blob/46a49680fdabfa1998ad9b76a5dafca43f2d2e4b/src/test/java/org/freedesktop/secret/simple/SimpleCollectionTest.java#L255) actually activates the service again.

Comment (swiesend) [reply src/main/java/org/freedesktop/secret/simple/SimpleCollection.java:223]: The [RegressionTest](https://github.com/swiesend/secret-service/blob/46a49680fdabfa1998ad9b76a5dafca43f2d2e4b/src/test/java/org/freedesktop/secret/integration/RegressionTests.java#L26) failed for the same reason. They expected the collection to be unlocked in order to test unrelated things.

**Comment by swiesend** [comment]
I will publish a new version soonish

**Comment by shocklateboy92** [comment]
Awesome! Thanks for the quick response.

**Comment by shocklateboy92** [comment]
So uh... you have a rough idea when you might find time to make a new release?

**Comment by swiesend** [comment]
Yes, I try to, but currently there is a nasty bug in https://mvnrepository.com/artifact/org.sonatype.plugins/nexus-staging-maven-plugin. I can stage a release on ossrh, but can't release it.

https://issues.sonatype.org/browse/NEXUS-26993

I also added https://github.com/swiesend/secret-service/commit/c3faa2d8987d4939c46af8249b681c3a8b1f4ff3 , which requires JDK 17. This will also break the semantic versioning, but I don't want to hold back this updates anymore...

**Comment by shocklateboy92** [comment]
Hey @swiesend , thanks for the release!
The team that owns the identity broker said it's way too difficult for them to upgrade to JDK17 at this time.

Is there any change I can get another release from commit [f265290](https://github.com/swiesend/secret-service/commit/f265290c0565abe3dbca1b425e96b3421e3c3893) as say, version `1.7.1`?
